# Generated by Django 5.1.4 on 2026-05-21 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('check_in', models.DateField(verbose_name='fecha de entrada')),
                ('check_out', models.DateField(verbose_name='fecha de salida')),
                ('guests_count', models.PositiveSmallIntegerField(verbose_name='número de huéspedes')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='precio total')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True, verbose_name='notas para el anfitrión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cabins.cabin', verbose_name='cabaña')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
