# Generated by Django 5.1.4 on 2026-05-21 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('size_sqm', models.PositiveIntegerField(help_text='Superficie en m²')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cabins/main/')),
                ('accent_color', models.CharField(default='#5e7c34', max_length=10)),
                ('tint', models.CharField(blank=True, max_length=300)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('experiences', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cabaña',
                'verbose_name_plural': 'cabañas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CabinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cabins/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cabins.cabin')),
            ],
            options={
                'verbose_name': 'imagen de cabaña',
                'verbose_name_plural': 'imágenes de cabaña',
                'ordering': ['order'],
            },
        ),
    ]
