# Generated by Django 5.1.4 on 2026-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen principal (cuando no hay archivo subido)'),
        ),
        migrations.AddField(
            model_name='cabinimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL externa cuando no hay archivo'),
        ),
        migrations.AlterField(
            model_name='cabinimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cabins/gallery/'),
        ),
    ]
